/**
 * The validation below is load-bearing. PyYAML's 1.1 resolver parses `312.0e12` as a
 * *string* (no exponent sign), which is why provider_loader.py had to coerce numeric
 * fields at runtime. The `yaml` package uses YAML 1.2 and parses it as a number — so we
 * assert the types here, turning a future `1e12` typo into a build failure rather than a
 * string silently entering a multiplication.
 */
import { readdirSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DATA = join(ROOT, "data");
const OUT = join(ROOT, "lib", "data", "generated.ts");

const errors = [];
const fail = (where, msg) => errors.push(`${where}: ${msg}`);

const isNum = (v) => typeof v === "number" && Number.isFinite(v);

function requireNum(obj, key, where) {
  if (!isNum(obj[key])) {
    fail(where, `"${key}" must be a number, got ${JSON.stringify(obj[key])} (${typeof obj[key]})`);
  }
}

const INSTANCE_NUMERIC = [
  "gpu_count",
  "peak_flops_fp16",
  "peak_flops_fp32",
  "memory_per_gpu",
  "total_gpu_memory",
  "vcpus",
  "system_memory",
  "network_bandwidth",
  "hourly_cost",
  "typical_mfu"
];

const instances = {};
const instanceOrder = [];
const storage = {};

for (const file of readdirSync(join(DATA, "providers"))
  .filter((f) => f.endsWith(".yaml"))
  .sort()) {
  const doc = parse(readFileSync(join(DATA, "providers", file), "utf8"));
  for (const [name, spec] of Object.entries(doc.instances ?? {})) {
    if (instances[name]) fail(file, `duplicate instance "${name}"`);
    for (const k of INSTANCE_NUMERIC) requireNum(spec, k, `${file}:${name}`);
    if (typeof spec.display_name !== "string")
      fail(`${file}:${name}`, "display_name must be a string");
    instances[name] = spec;
    instanceOrder.push(name);
  }
  for (const [name, spec] of Object.entries(doc.storage ?? {})) {
    requireNum(spec, "cost_per_tb_month", `${file}:storage:${name}`);
    storage[name] = spec.cost_per_tb_month;
  }
}

if (!instanceOrder.length) fail("data/providers", "no instances found");

const models = [];

for (const file of readdirSync(join(DATA, "models"))
  .filter((f) => f.endsWith(".yaml"))
  .sort()) {
  const doc = parse(readFileSync(join(DATA, "models", file), "utf8"));
  const where = `data/models/${file}`;
  const slug = basename(file, ".yaml");

  for (const k of ["name", "slug", "family"]) {
    if (typeof doc[k] !== "string") fail(where, `"${k}" is required and must be a string`);
  }
  if (doc.slug !== slug) fail(where, `slug "${doc.slug}" must match the filename "${slug}"`);
  requireNum(doc, "parameter_count", where);

  const arch = doc.architecture ?? {};
  // The README promises MoE FLOPs are costed on active params. Without this field they
  // silently aren't — which was a real bug (DeepSeek V3 costed at 671B, not 37B).
  if (arch.moe && !isNum(arch.moe.active_parameter_count)) {
    fail(where, "architecture.moe requires a numeric active_parameter_count");
  }

  models.push({
    name: doc.name,
    slug: doc.slug,
    family: doc.family,
    parameter_count: doc.parameter_count,
    architecture: arch,
    source: doc.source ?? "",
    notes: String(doc.notes ?? "")
  });
}

models.sort((a, b) => a.parameter_count - b.parameter_count);

if (errors.length) {
  console.error("build-data failed:\n" + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}

const banner = `// GENERATED by scripts/build-data.mjs — do not edit, do not commit.
// Source: data/models/*.yaml, data/providers/*.yaml
`;

const body = `${banner}
import type { InstanceSpec, ModelDefinition } from "../engine/types";

/** Instance keys in YAML order. The default instance is INSTANCE_ORDER[0]; relying on
 *  object key order for that would be fragile. */
export const INSTANCE_ORDER: readonly string[] = ${JSON.stringify(instanceOrder, null, 2)};

export const AWS_GPU_INSTANCES: Record<string, InstanceSpec> = ${JSON.stringify(instances, null, 2)};

export const S3_STORAGE_PRICING: Record<string, number> = ${JSON.stringify(storage, null, 2)};

/** Sorted by parameter_count, matching load_models(). */
export const MODELS: ModelDefinition[] = ${JSON.stringify(models, null, 2)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(
  `  lib/data/generated.ts: ${instanceOrder.length} instances, ` +
    `${Object.keys(storage).length} storage classes, ${models.length} models`
);
